### ISSUE TITLE
Redundant parentheses cause an error 

### ISSUE THREAD

**Issue by papajin** [sarfraznawaz2005/visitlog#14]
`$ip = (app('VisitLog'))->getUserIP();` - this causes an error on PHP5.6.40 (`syntax error, unexpected '->' (T_OBJECT_OPERATOR)`)
Parentheses are here redundant. Aren't they?
This is in Sarfraznawaz2005\VisitLog\Middleware\ipCheckMiddleware class.

**Comment by sarfraznawaz2005** [comment]
Can you remove those parenthesis and see if it makes difference ? I will remove these once you confirm.

**Comment by papajin** [comment]
Without parentheses it does work (i.e. works like a charm). 
You can try in tinker with and without the parentheses to see the difference.

**Comment by sarfraznawaz2005** [comment]
okay thanks, fixed with release 1.3.2

**Comment by papajin** [comment]
Thanks Sarfaz!
And once again thanks for the great library.
