### ISSUE TITLE
Fails installation for Laravel 7.19.1

### ISSUE THREAD

**Issue by muaz234** [sarfraznawaz2005/visitlog#15]
Hi, 

Can I know if anyone could install this package using latest laravel version? Is there any workaround for this? Installation is done using Cmder with Windows 10 operating system.

![error stack trace](https://user-images.githubusercontent.com/36180180/87251317-58fb5f80-c49d-11ea-8c55-d759d43dc385.png)

**Comment by sarfraznawaz2005** [comment]
try again plz
