### ISSUE TITLE
I can't change middleware

### ISSUE THREAD

**Issue by Bagmaz** [sarfraznawaz2005/visitlog#2]
I want show visitLog only Admin user, how can i do?

**Comment by sarfraznawaz2005** [comment]
If you want to show visitlogs in your own way (in this case to admins only), you can set `visitlog_page`  in `config/visitlog.php` to `false` to disable default viewer page.

Later on your app, you can use `VisitLog` facade to get all visit log entries from database and show them however you like something like:

```
if (! $user->isAdmin()) {
  // show 404 to non-admins
  abort();
}

$visitLogs = VisitLog::all();
// pass $visitLogs to your custom view and iterate over them in your table/whatever
```

**Comment by Bagmaz** [comment]
I did the same, but i can't set VisitLog::latest()->paginate(10);
VisitLog::orderBy('name', 'desc')->get();
or something, Why?

**Comment by sarfraznawaz2005** [comment]
because `Facade` does not have `latest` method. You need to use its model so change:

`use Sarfraznawaz2005\VisitLog\Facades\VisitLog;`

to

`use Sarfraznawaz2005\VisitLog\Models\VisitLog;`

and then you can do `$visitLogs = VisitLog::latest()->paginate(10);`

**Comment by Bagmaz** [comment]
Thank you so much, It's helpful
This is very good for me.
