### ISSUE TITLE
IP location alternative to use freegeoip

### ISSUE THREAD

**Issue by ip2location-com** [sarfraznawaz2005/visitlog#26]
We are pleased to present a different IP location service called [IP2Location.io](https://www.ip2location.io). You can use it for up to 500 free IP location searches daily without needing an API key. By signing up for a free API plan and using the provided API key, you can access 30,000 IP location queries. Check out the API documentation at [https://www.ip2location.io/ip2location-documentation](https://www.ip2location.io/ip2location-documentation).

Kindly consider using the IP2Location.io API for your project.

**Comment by sarfraznawaz2005** [comment]
please send pr
