### ISSUE TITLE
How to log for new record, even with same IP?

### ISSUE THREAD

**Issue by blu94** [sarfraznawaz2005/visitlog#4]
I have to log a new record from same IP, but different date, how can i do it?

**Comment by sarfraznawaz2005** [comment]
@blu94 First of you would need to set 'unique' option to `false` and then modify `visitlog/src/VisitLog.php`'s `save()` method so it considers differnent dates only when saving as there is no built-in functionality currently. Currenly it can only be unique IPs or same IPs any number of times on same day.
