### ISSUE TITLE
error ""trim() expects parameter 1 to be string, array given"

### ISSUE THREAD

**Issue by jjoek** [sarfraznawaz2005/visitlog#7]
{message: "trim() expects parameter 1 to be string, array given", exception: "ErrorException",…}
exception: "ErrorException"
file: "/home/jjoek/Documents/projects/centric/vendor/sarfraznawaz2005/visitlog/src/VisitLog.php"
line: 139
message: "trim() expects parameter 1 to be string, array given"
trace: [{function: "handleError", class: "Illuminate\Foundation\Bootstrap\HandleExceptions", type: "->"},…]

**Comment by sarfraznawaz2005** [comment]
can you please tell which version of Laravel you are using.

**Comment by sarfraznawaz2005** [comment]
please try again.

**Comment by oelsuser** [comment]
i am facing same issue and iam using laravel 5.8. please help me on that
