### ISSUE TITLE
trim() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by oelsuser** [sarfraznawaz2005/visitlog#8]
I am using Laravel 5.8 and im getting error ""trim() expects parameter 1 to be string, array given".After commenting this mentioned piece of code, it works properly.
 if (is_array($data)) {
       $data = array_map('trim', $data);
  }
Please help me on that asap

**Comment by sarfraznawaz2005** [comment]
@oelsuser just keep it commented, that piece of code is not necessary.  I will update the code shortly.
